INSERT INTO bierre VALUES(1,'Bonne','Leffe blonde', 12, 'blonde');
INSERT INTO bierre VALUES(2,'moyenne','Kasteel', 8, 'brune');
INSERT INTO bierre VALUES(3,'corsée','Fischer ambrée', 18, 'ambree');
INSERT INTO bierre VALUES(4,'corsée','Pelforth brune', 18, 'brune');
INSERT INTO bierre VALUES(5,'corsée','Biere de meaux', 18, 'brune');
INSERT INTO bierre VALUES(6,'corsée','Goliath', 18, 'brune');
INSERT INTO bierre VALUES(7,'corsée','Mc chouffe', 18, 'brune');
INSERT INTO bierre VALUES(8,'corsée','Gauloise blonde', 18, 'blonde');
INSERT INTO bierre VALUES(9,'corsée','Lager', 18, 'blonde');
INSERT INTO bierre VALUES(10,'corsée','Aubrac blonde', 18, 'blonde');
INSERT INTO bierre VALUES(11,'corsée','Jenlain', 18, 'ambree');
INSERT INTO bierre VALUES(12,'corsée','Ninkasi ambrée', 18, 'ambree');
